#!/bin/bash
# Manual Deployment Steps - Run These Commands in Terminal

echo "==============================================="
echo "🚀 MERCHANT CHAT SUPPORT - BACKEND DEPLOYMENT"
echo "==============================================="
echo ""
echo "Copy and paste these commands into your terminal:"
echo ""
echo "# Step 1: Navigate to backend directory"
echo "cd /Users/ghaythallaheebi/WhizzEcoSystem/whizzEcosystem/whizzCentralPlatform/backend"
echo ""
echo "# Step 2: Clean up"
echo "rm -rf temp-deploy chat-websocket-handler-deployment.zip"
echo ""
echo "# Step 3: Create deployment structure"
echo "mkdir -p temp-deploy/src/handlers"
echo ""
echo "# Step 4: Copy files"
echo "cp src/handlers/chat-websocket-handler.js temp-deploy/src/handlers/"
echo "cp package.json temp-deploy/"
echo ""
echo "# Step 5: Install dependencies"
echo "cd temp-deploy"
echo "npm install --production"
echo ""
echo "# Step 6: Create ZIP"
echo "zip -r ../chat-websocket-handler-deployment.zip ."
echo "cd .."
echo ""
echo "# Step 7: Deploy to AWS"
echo "aws lambda update-function-code \\"
echo "  --function-name chat-websocket-handler \\"
echo "  --zip-file fileb://chat-websocket-handler-deployment.zip \\"
echo "  --region us-east-1"
echo ""
echo "==============================================="
echo "✅ After deployment, test the fix:"
echo "   1. Open: http://localhost:3000/pages/support.html"
echo "   2. Send message from merchant app"
echo "   3. Verify session appears on dashboard"
echo "==============================================="
