#!/bin/bash

echo "🔄 IMPORTANT: Refresh the Browser Page!"
echo "=========================================="
echo ""
echo "The function is now exposed to window, but you need to:"
echo ""
echo "1. ⚠️  Hard refresh the page in your browser:"
echo "   • Chrome/Edge: Cmd + Shift + R"
echo "   • Safari: Cmd + Option + R"
echo ""
echo "2. Open Browser Console (F12 or Cmd + Option + I)"
echo ""
echo "3. Check for this log:"
echo "   ✅ sendMerchantInfoNotification exposed to window"
echo ""
echo "4. Test the function is available:"
echo "   typeof window.sendMerchantInfoNotification"
echo "   Should show: 'function'"
echo ""
echo "5. Try clicking 'Send to Merchants' again"
echo ""
echo "=========================================="
echo ""
echo "If you still see nothing happen:"
echo "• Check console for errors (red text)"
echo "• Look for the debug log: '🔥 sendMerchantInfoNotification called!'"
echo "• If you don't see that log, the function isn't being called"
echo ""
echo "URL: http://localhost:3000/pages/promotions.html"
echo ""
