#!/bin/zsh

echo "📥 Firebase Service Account Setup Guide"
echo "========================================"
echo ""
echo "To use Firebase Cloud Messaging API V1, you need to download the service account key."
echo ""
echo "🔍 Step-by-Step Instructions:"
echo ""
echo "1. Go to Firebase Console:"
echo "   https://console.firebase.google.com/"
echo ""
echo "2. Select your project: 'wizz business'"
echo ""
echo "3. Click the ⚙️ (Settings) icon → 'Project settings'"
echo ""
echo "4. Go to 'Service accounts' tab"
echo ""
echo "5. Click 'Generate new private key' button"
echo ""
echo "6. Click 'Generate key' in the confirmation dialog"
echo ""
echo "7. Save the JSON file as:"
echo "   /Users/ghaythallaheebi/WhizzEcoSystem/whizzEcosystem/whizzCentralPlatform/backend/lambda/firebase-service-account.json"
echo ""
echo "8. DO NOT commit this file to git (it's sensitive!)"
echo ""
echo "Once you have the file, run:"
echo "   ./deploy-fcm-v1-update.sh"
echo ""
echo "🔐 Security Note:"
echo "The service account key will be stored securely in AWS Lambda environment variables."
echo ""
